const ADD_FAVORITES = "ADD_FAVORITES";
const DELETE_FAVORITES = "DELETE_FAVORITES";
const ORDER = "ORDER";
const FILTER = "FILTER";

export {
    ADD_FAVORITES,
    DELETE_FAVORITES,
    ORDER,
    FILTER
}